### ISSUE TITLE
Exception when running "Value IDs" check in DB analyzer using SQLite

### ISSUE THREAD

**Issue by supermihi** [maestromusic/maestro#36]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "LEFT": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michael/code/maestro/maestro/plugins/dbanalyzer/plugin.py", line 240, in _handleFixButton
    self.currentCheck.fix()
  File "/home/michael/code/maestro/maestro/plugins/dbanalyzer/checks.py", line 67, in fix
    self._fix()
  File "/home/michael/code/maestro/maestro/plugins/dbanalyzer/checks.py", line 266, in _fix
    db.query(self._query(type.name, False, True))
  File "/home/michael/code/maestro/maestro/database/__init__.py", line 208, in query
    result = engine.execute(queryString, _args)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1989, in execute
    return connection.execute(statement, *multiparams, *_params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "LEFT": syntax error [SQL: "DELETE\n            FROM tags LEFT JOIN values_varchar ON tags.tag_id = values_varchar.tag_id\n                                                 AND tags.value_id = values_varchar.id\n                  WHERE tags.tag_id IN (SELECT id FROM tagids WHERE tagtype = 'varchar') AND id IS NULL\n            "]

**Comment by supermihi** [comment]
Sorry, the issue still persists:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "tags": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michael/code/maestro/maestro/plugins/dbanalyzer/plugin.py", line 240, in _handleFixButton
    self.currentCheck.fix()
  File "/home/michael/code/maestro/maestro/plugins/dbanalyzer/checks.py", line 67, in fix
    self._fix()
  File "/home/michael/code/maestro/maestro/plugins/dbanalyzer/checks.py", line 266, in _fix
    db.query(self._query(type.name, False, True))
  File "/home/michael/code/maestro/maestro/database/__init__.py", line 209, in query
    result = engine.execute(queryString, *args)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1987, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "tags": syntax error [SQL: "DELETE tags\n            FROM tags LEFT JOIN values_varchar ON tags.tag_id = values_varchar.tag_id\n                                                 AND tags.value_id = values_varchar.id\n                  WHERE tags.tag_id IN (SELECT id FROM tagids WHERE tagtype = 'varchar') AND id IS NULL\n            "]
2015-07-05 19:31:38,789: DEBUG - maestro.filesystem.sources - Adding 1 new file hashes to the database
2015-07-05 19:31:38,832: DEBUG - maestro.filesystem.sources - scan of source musik finished
```
